# Generated by Django 3.0.2 on 2020-01-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='test', max_length=160),
            preserve_default=False,
        ),
    ]
