# Generated by Django 3.0.8 on 2020-07-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
