# Generated by Django 3.0.8 on 2020-07-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20200710_1116'),
        ('posts', '0004_auto_20200703_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='media.Media'),
        ),
    ]
