# Generated by Django 3.0.8 on 2020-07-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=155)),
                ('alt', models.SlugField(editable=False)),
                ('full', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('full_jpeg', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('mobile', models.ImageField(editable=False, upload_to='uploads/%Y/%m/%d/', width_field=500)),
                ('mobile_jpeg', models.ImageField(editable=False, upload_to='uploads/%Y/%m/%d/', width_field=500)),
                ('prev', models.ImageField(editable=False, upload_to='uploads/%Y/%m/%d/', width_field=100)),
            ],
        ),
    ]
